### ISSUE TITLE
Dealer locator - Distance Sorting

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-au#16]
### Description
This issue is a follow-up of issue [DL 1: Dealer Locator - Export, AU/NZ](https://github.com/hlxsites/vg-macktrucks-com/issues/439).

As per the last comment from Becky on the above issue, the list of dealers has to be sorted by distance. With the current implementation, once a user enables location the page needs to be manually refreshed for dealers to be sorted according to distance to the user's location. This issue aims to have the block automatically refresh the list, hence not needing the user to manually reload the page.

### Acceptance Criteria

- [ ] Once a user enables location, dealers are sorted based on the distance to the user without further action from the user.

**Comment by girishdigrajkar** [comment]
Validated and able to get the expected results hence, marking this ticket as done.

Bydefault/ when location is blocked:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-au/assets/125972657/d36a02f6-6ff9-4eae-965e-703fbb6338e8">

When location is allowed :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-au/assets/125972657/55cb8a89-1cc1-402c-8b8f-faa4eae42330">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-au/assets/125972657/d66a0556-b8f0-4ffd-974b-1abe91edb8c4">
