### ISSUE TITLE
Macktrucks AU Site consolidated issues 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com-au#18]
**Content issues:**
- [ ] 1. Homepage: Explore block does not have registered or trademark signs as expected.
- [x] 2.  Homepage: Community section name is not horizontally aligned to centre 
- [x] 3.  Homepage: Community section: ‘READ THE MACK BLOG’  button when clicked shows no content as not authored/published
- [x] 4. Footer block : Click on ‘Request a quote’ > page is not displayed
- [ ] 5.  Footer block:  Youtube , Instagram icons are not displayed; Also there is a gap of a line between Mack logo and icons
- [x] 6. Below Footer menus are not listed: 7. Mack News, 2023 Labor Negotiations, Emissions Info,	SDS Info. Link ‘Change Country’ placement position is changed  &, Link ‘Events’ is being displayed unlike that on [mactrucks.com](http://mactrucks.com/)
- [x] 7. Footer:  Content not authored / published for ‘Contact Us’ link 
- [ ] 8.  Footer : Cookies, Privacy, Terms & Conditions, ‘Do Not Sell or Share My Personal Information’  links are not displayed
- [x] 9.  Homepage: Click on Trucks menu :  Truck model names are not visible until hoverer; Font size is not as expected
- [ ] 10.  Homepage: Click on Trucks menu : ‘Build Yours’ button is not displayed
- [x] 11.  Trucks >>  Mack Lineup > Click on ‘View All Trucks >’ >>  Sub navigation menu is not displayed  :  This is throughout the site 
- [x] 12.  Homepage : Click on ‘Parts & Services’ Menu > Menu Accordion is not displayed
- [x] 13. Homepage >> ‘Built in Australia’  menu does not have ‘Bulldog Magazine’ section and its links 
- [ ] 14. https://www.macktrucks.com.au/about-mack/facilities/  content is not available/not published
- [ ] 15. Homepage >> ‘Built in Australia’  menu does not have ‘ABOUT MACK’ section and its sub menus/links 

**Code issues:**
- [ ] 1. Cookie integration is not completed

**Comment by jonatan-lledo-netcentric** [comment]
1. The only Trademark That I know is the Anthem model. if the others also have it it needs to be asked to the client to let us know if any of the other models also need that icon
2. Community title now is centred
3. the button now goes to the magazine
4. the button has been removed
5. YouTube and Instagram now are there, but the gap is because this footer has fewer links
6. As I said in the previous point, this site has fewer links and doesn't need to have the same amount of them in every market
7. The Contact Us page is published

**Comment by jonatan-lledo-netcentric** [comment]
### Code issues
1. This is a Dependency because our side already implemented the code. Is their responsibility because we don't have access to OneTrust. The only change that we can make is to update the OneTrust ID if it is not correct, and even this is a dependency if the ID provided is wrong

**Comment by BeckyMedlin** [comment]
@Kannan-CM Please provide status of this ticket. Thank you!

**Comment by Kannan-CM** [comment]
Will follow up with ticket #8
