### ISSUE TITLE
Testing: Site testing for MackTrucks AU (QA & UAT)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-au#2]
Testing in full all pages/sections of the site.
This issue is for both QA testing and UAT.

**Comment by DanielaPedrochevd** [comment]
Dependant of content readiness

**Comment by girishdigrajkar** [comment]
Validation completed for Homepage and Find a dealer page only...

**Comment by Kannan-CM** [comment]
Pending issue related to YouTube videos. 
JIRA ticket reference:

https://projects.netcentric.biz/browse/VOLVOOPS-5161

**Comment by BeckyMedlin** [comment]
@Kannan-CM Do you mean this one is blocked until https://projects.netcentric.biz/browse/VOLVOOPS-5161 is resolved?

**Comment by Kannan-CM** [comment]
Yes @BeckyMedlin ,
That, we need that issue resolved.. that bug is part of the Migration activity.
