### ISSUE TITLE
Macktrucks AU website DOWN

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com-au#28]
### Issue Type

Bug

### Summary

Mack AU website pages look empty

### Priority

Blocker

### Description

Navigating to https://www.macktrucks.com.au/ needs to display page content. But it looks empty

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Chrome V125

### Steps to Reproduce

Navigating to https://www.macktrucks.com.au/

### Expected Results

Page should display contnet

### Actual Results

Page is empty

**Comment by BeckyMedlin** [comment]
Macktrucks.au is down. @dkuntze @verareljic

**Comment by ZoeBeykirch** [comment]
The AU website is back up, but the search icon is present in the nav bar and leading to a 404 error -https://www.macktrucks.com.au/search
Search should be disabled for all market sites

**Comment by santi-homps** [comment]
This should be fixed with PRs for [MACK](https://github.com/hlxsites/vg-macktrucks-com/pull/758) and [VOLVO](https://github.com/hlxsites/vg-volvotrucks-us/pull/661)
