### ISSUE TITLE
NFR: Configure analytics/tracking (GTM, FB Pixel)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-au#7]
This is part of the GoLive activities.

**Comment by manuel-vara** [comment]
GTM code of AUS:  **GTM-K6KJGCW**

**Comment by Kannan-CM** [comment]
OneTrust script for AU:


<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="cfb3642f-723b-40b4-8af8-ca9252e753b4" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
Hi @jonatan-lledo-netcentric ,

The analytics is not loading on the AU site. Could you please validate the set up on your end?

Kind regards,
Kannan C

**Comment by ZoeBeykirch** [comment]
AU analytics is not working at all, we are not clear on IF it is onetrust or a code issue, but it needs to be resolved as they are blocked on running paid campaigns until this is fixed.

**Comment by jonatan-lledo-netcentric** [comment]
The code in the delayed.js script is equivalent at the .com. The only difference is the optanon id. If the ID is incorrect, it needs to be updated @Kannan-CM. so, please, can you check the id if it is correct? because it was copied from the previous [comment](https://github.com/hlxsites/vg-macktrucks-com-au/issues/7#issuecomment-1809951731). Thanks

**Comment by jonatan-lledo-netcentric** [comment]
The last PR it's just temporary. As soon @Kannan-CM confirm that OneTrust was able to do its scan, we're going to revert the last Update

**Comment by Kannan-CM** [comment]
HI @jonatan-lledo-netcentric ,

AU is running a campaign and we would like to have the Google Anlaytics working for it.

Could you please let the Google analytics load on their site?

**Comment by jonatan-lledo-netcentric** [comment]
> HI @jonatan-lledo-netcentric ,
> 
> AU is running a campaign and we would like to have the Google Anlaytics working for it.
> 
> Could you please let the Google analytics load on their site?

As soon as it's needed, I'll update this to how it was before. Also, please confirm if FB Pixel is still necessary and I can remove it in the same update. Thanks

@Kannan-CM

**Comment by girishdigrajkar** [comment]
Able to see the correct code & script however, There are no ACs related to cookie integration & resulting codes /script upon selection criteria...  (**Current state : No cookies checked and script & code are injected  -- Future state is not yet defined   confirmed implementation with @jonatan-lledo-netcentric** ) 

@ZoeBeykirch @Kannan-CM @Shirin, @Molly @jonatan-lledo-netcentric @verareljic : Outstanding points need to be addressed.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-au/assets/125972657/be3ad20c-4106-4071-9f10-2213ebe8151d">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-au/assets/125972657/1f2e0743-85bb-481c-8dcd-67a80e86c613">

**Comment by girishdigrajkar** [comment]
@Kannan-CM :  Kindly reassign this defect once AU marketing campaign is done.
